/** Metadata for a captured test clip. */
export const clipTestMetadata = {
  schema_version: 1,
  clip_id: '01KYFX6NFRDVW03ZFJXQ6W1VVG',
  title: 't',
  url: 'https://example.com/',
  normalized_url: 'https://example.com/',
  canonical_url: null,
  site: 'example.com',
  author: null,
  published: null,
  language: 'en',
  clipped_at: '2026-07-26T19:07:35Z',
  clipped_from: 'test',
  extension_version: '0.1.0',
  extractor: 'defuddle',
  extractor_version: '0.6.0',
  snapshot_mode: 'sanitized',
  sensitivity: 'public',
  content_sha256: 'a'.repeat(64),
  source_html_sha256: 'b'.repeat(64),
  asset_count: 0,
  asset_failures: [],
  note: '',
  tags: [],
  word_count: 10,
}
